#!/bin/sh

if [ -z "$LT_HOME" ]
then
  # Find the first application bundle known to the system, the application bundle itself is already a directory
  APP_DIR=$(mdfind kMDItemCFBundleIdentifier == com.kodowa.LightTable | head -n 1)
else
  APP_DIR="${LT_HOME}/LightTable.app"
fi
if [ ! -d "$APP_DIR" ]
then
	echo "Sorry, cannot find LightTable.app.  Try setting the LT_HOME environment variable to the directory containing LightTable.app."
	exit 1
fi

LTCLI=true "${APP_DIR}/Contents/MacOS/Electron" "$@" &
